# configs/sb3_sac.yaml
env:
  n_envs: 4
  max_episode_steps: 720 # env의 done 기준과 통일
  seed: 42
  vec_norm_obs: true
  vec_norm_reward: false
  clip_obs: 5.0
  sim:
    num_zones: 4
  stats_window_size: 10000

sac:
  learning_rate: 3.0e-4
  buffer_size: 500000
  batch_size: 256
  tau: 0.005
  gamma: 0.995 # ← 느린 열동역학 반영
  train_freq: 1
  gradient_steps: 1
  learning_starts: 5000
  ent_coef: "auto_0.1"
  target_entropy: "auto"

policy:
  net_arch: [256, 256]
  activation_fn: "ReLU"
  log_std_init: -1.0
  use_sde: false

train:
  total_timesteps: 1200000 # 1.2M 권장 (수렴 안정)
  eval_freq: 10000
  n_eval_episodes: 5
  save_freq: 50000
  checkpoint_path: "checkpoints/sb3_sac"
  tensorboard_log: "logs/sb3_sac"

# 평가/체크포인트
eval:
  eval_freq: 10000
  n_eval_episodes: 5
  deterministic: true
  best_model_save_path: checkpoints/sb3_sac
  log_path: logs/sb3_sac
  sync_vecnormalize: true
  fixed_targets: [24.0, 25.0, 26.0, 25.0]
